# Generated by Django 5.1 on 2024-08-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
