# Generated by Django 5.1 on 2024-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0005_userprofile_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
