# Generated by Django 5.1 on 2024-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0005_serviceavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceAvailability',
        ),
    ]
