# Generated by Django 5.1 on 2024-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0006_usersignup_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
