# Generated by Django 5.1 on 2024-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0006_delete_serviceavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
