# Generated by Django 5.1 on 2024-09-24 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0007_usersignup_reset_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('task_month', models.CharField(choices=[('6-12', '6-12 Months Before'), ('4-6', '4-6 Months Before'), ('2-4', '2-4 Months Before'), ('1-2', '1-2 Months Before'), ('1-2 Weeks', '1-2 Weeks Before'), ('Final Days', 'Final Days'), ('Wedding Day', 'Wedding Day')], default='6-12', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_predefined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamknot1.usersignup')),
            ],
        ),
    ]
