# Generated by Django 5.1 on 2024-09-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0008_weddingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('wedding_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamknot1.usersignup')),
            ],
        ),
    ]
