# Generated by Django 5.1 on 2024-10-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0009_booking_canceled_by_user_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
