# Generated by Django 5.1 on 2024-09-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0010_service_booking_serviceimage_rating_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dreamknot1.vendorprofile')),
            ],
        ),
    ]
