# Generated by Django 5.1 on 2024-10-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0010_service_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_main_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Catering', 'Catering'), ('Venue', 'Venue'), ('Decoration', 'Decoration'), ('MusicEntertainment', 'Music & Entertainment'), ('MakeupHair', 'Makeup & Hair'), ('Rentals', 'Rentals'), ('MehendiArtist', 'Mehendi Artist')], max_length=255),
        ),
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_planning', models.TextField()),
                ('meal_service_type', models.CharField(choices=[('Buffet', 'Buffet'), ('Plated', 'Plated'), ('Food Stations', 'Food Stations')], max_length=50)),
                ('dietary_options', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_guest_count', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor_themes', models.TextField()),
                ('floral_arrangements', models.BooleanField(default=False)),
                ('lighting_options', models.BooleanField(default=False)),
                ('stage_decor', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupHairService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooming_services', models.TextField()),
                ('trial_sessions', models.BooleanField(default=False)),
                ('high_end_products', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_hair_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='MehendiArtistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_styles', models.TextField()),
                ('duration_per_hand', models.DecimalField(decimal_places=2, max_digits=5)),
                ('use_of_organic_henna', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mehendi_artist_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='MusicEntertainmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_options', models.TextField()),
                ('sound_system_setup', models.BooleanField(default=False)),
                ('multiple_entertainment_acts', models.BooleanField(default=False)),
                ('emcee_services', models.BooleanField(default=False)),
                ('playlist_customization', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_entertainment_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_duration', models.CharField(choices=[('Half-day', 'Half-day'), ('Full-day', 'Full-day')], max_length=50)),
                ('styles', models.TextField()),
                ('engagement_shoots', models.BooleanField(default=False)),
                ('videography_options', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='RentalsService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_items', models.TextField()),
                ('setup_services', models.BooleanField(default=False)),
                ('rental_price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_of_rental', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_services', to='dreamknot1.service')),
            ],
        ),
        migrations.CreateModel(
            name='VenueService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_venue', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Destination', 'Destination')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('pre_post_wedding_availability', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_services', to='dreamknot1.service')),
            ],
        ),
    ]
