# Generated by Django 5.1 on 2024-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0011_booking_event_address_vendorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingtask',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
