# Generated by Django 5.1 on 2024-09-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0012_weddingtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamknot1.usersignup'),
        ),
    ]
