# Generated by Django 5.1 on 2025-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0014_booking_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Completed'), (3, 'Canceled'), (4, 'Refunded')], default=0),
        ),
    ]
