# Generated by Django 5.1 on 2025-01-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0015_alter_booking_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_social_user',
            field=models.BooleanField(default=False),
        ),
    ]
