# Generated by Django 5.1 on 2025-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0016_usersignup_is_social_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
