# Generated by Django 5.1 on 2025-01-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0017_usersignup_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text_feedback', models.TextField()),
                ('feedback_type', models.CharField(choices=[('service_quality', 'Service Quality'), ('communication', 'Communication'), ('value_for_money', 'Value for Money'), ('professionalism', 'Professionalism'), ('overall', 'Overall Experience')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamknot1.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dreamknot1.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamknot1.usersignup')),
            ],
            options={
                'unique_together': {('booking', 'feedback_type')},
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_score', models.FloatField()),
                ('positive_score', models.FloatField()),
                ('negative_score', models.FloatField()),
                ('neutral_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.JSONField(default=dict)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='dreamknot1.servicefeedback')),
            ],
        ),
        migrations.CreateModel(
            name='VendorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('sentiment_summary', models.JSONField(default=dict)),
                ('common_feedback_topics', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='dreamknot1.vendorprofile')),
            ],
        ),
    ]
