# Generated by Django 5.1 on 2025-02-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0019_vendorrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorRecommendation',
        ),
    ]
