# Generated by Django 5.1 on 2025-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0021_weddingbudget_budgetallocation_weddingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Must Have'), (2, 'Nice to Have'), (3, 'If Budget Allows')], default=2),
        ),
    ]
