# Generated by Django 5.1 on 2025-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0022_alter_budgetallocation_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]),
        ),
    ]
