# Generated by Django 5.1 on 2025-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0023_alter_budgetallocation_priority_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddingevent',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
