# Generated by Django 5.1 on 2025-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0024_alter_weddingevent_options_weddingevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingevent',
            name='detailed_budget',
            field=models.JSONField(default=dict),
        ),
    ]
