# Generated by Django 5.1 on 2025-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0026_remove_weddingevent_detailed_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='category',
            field=models.CharField(choices=[('Venue', 'Venue'), ('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photography', 'Photography'), ('Attire', 'Attire'), ('Entertainment', 'Entertainment'), ('Mehendi', 'Mehendi'), ('MakeupHair', 'Makeup')], max_length=50),
        ),
    ]
