# Generated by Django 5.1 on 2025-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamknot1', '0027_alter_budgetallocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='category',
            field=models.CharField(choices=[('Venue', 'Venue'), ('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Photography', 'Photography'), ('Attire', 'Attire'), ('Entertainment', 'Entertainment'), ('Mehendi', 'Mehendi'), ('MakeupHair', 'Makeup & Hair')], max_length=50),
        ),
    ]
